from __future__ import annotations

from collections.abc import Iterable
from typing import Any

VALID_DECISIONS = {"allow", "prompt", "forbidden"}


def _starlark_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _starlark_list(items: list[str]) -> str:
    return "[" + ", ".join(_starlark_string(i) for i in items) + "]"


def translate_rules(
    rules_by_name: Iterable[tuple[str, Any]],
) -> tuple[str | None, list[str]]:
    """Translate `codex:rules` into Starlark `prefix_rule(...)` fragments."""
    lines: list[str] = ["# Generated by coding-agents sync"]
    warnings: list[str] = []
    seen: set[tuple[tuple[str, ...], str]] = set()
    emitted = False

    for name, rules in sorted(rules_by_name, key=lambda item: item[0]):
        if isinstance(rules, dict):
            rules = [rules]
        if not isinstance(rules, list):
            continue
        for rule in rules:
            if not isinstance(rule, dict):
                warnings.append(f"{name}: skipped codex:rules entry, not a mapping")
                continue
            pattern = rule.get("pattern")
            if (
                not isinstance(pattern, list)
                or not pattern
                or not all(isinstance(item, str) for item in pattern)
            ):
                warnings.append(
                    f"{name}: skipped codex:rules entry because `pattern` must "
                    "be a non-empty list of strings"
                )
                continue
            decision = rule.get("decision", "allow")
            if decision not in VALID_DECISIONS:
                warnings.append(
                    f"{name}: skipped codex:rules entry because `decision` must "
                    f"be one of {sorted(VALID_DECISIONS)}"
                )
                continue
            key = (tuple(pattern), decision)
            if key in seen:
                continue
            seen.add(key)
            call_args = [
                f"pattern={_starlark_list(pattern)}",
                f"decision={_starlark_string(decision)}",
            ]
            justification = rule.get("justification")
            if isinstance(justification, str) and justification:
                call_args.append(f"justification={_starlark_string(justification)}")
            lines.append(f"prefix_rule({', '.join(call_args)})")
            emitted = True

    if not emitted:
        return None, warnings
    return "\n".join(lines) + "\n", warnings
