from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

import tomlkit
from pydantic import AliasChoices, ConfigDict, Field

from ..models import SyncContext
from ..patches import Patch, validate_generated_conflicts
from ..plan import (
    Diagnostic,
    ManifestMode,
    NativePatch,
    NativeValue,
    OwnedFile,
    OwnedTree,
    Plan,
)
from ..sources import AgentSource, SkillSource, SourceBundle, StrictModel
from .support import (
    applies_to,
    block,
    bundled_files,
    frontmatter,
    native_patch,
    omissions,
    raw_files,
    strict_native,
    unhandled_target_block,
)


class CodexPrefixRule(StrictModel):
    pattern: list[str] = Field(min_length=1)
    decision: Literal["allow", "prompt", "forbidden"] = "allow"
    justification: str | None = None


class CodexRuleNative(StrictModel):
    rules: list[CodexPrefixRule] = Field(default_factory=list)


class CodexSkillNative(StrictModel):
    model_config = ConfigDict(extra="forbid", frozen=True, populate_by_name=True)

    name: str | None = None
    description: str | None = None
    license: str | None = None
    metadata: dict[str, Any] | None = None
    allowed_tools: list[str] | None = Field(
        None,
        serialization_alias="allowed-tools",
        validation_alias=AliasChoices("allowed-tools", "allowed_tools"),
    )


class CodexAgentNative(StrictModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    name: str | None = None
    description: str | None = None
    developer_instructions: str | None = None
    model: str | None = None
    model_reasoning_effort: str | None = None
    sandbox_mode: str | None = None
    nickname_candidates: list[str] | None = None


def _tree(skill: SkillSource, root: Path, meta: dict[str, Any]) -> OwnedTree:
    files, executables = bundled_files(skill.source_dir)
    import yaml

    header = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True).rstrip()
    files[Path("SKILL.md")] = f"---\n{header}\n---\n\n{skill.body.rstrip()}\n".encode()
    return OwnedTree(
        root / skill.source_dir.name,
        tuple(sorted(files.items())),
        root,
        executables=executables,
    )


def _rule_text(rules: list[tuple[str, CodexPrefixRule]]) -> bytes | None:
    if not rules:
        return None
    lines = ["# Generated by coding-agents sync"]

    def quoted(value: str) -> str:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    for _, rule in sorted(rules):
        pattern = "[" + ", ".join(quoted(item) for item in rule.pattern) + "]"
        args = [f"pattern={pattern}", f"decision={quoted(rule.decision)}"]
        if rule.justification:
            args.append(f"justification={quoted(rule.justification)}")
        lines.append(f"prefix_rule({', '.join(args)})")
    return ("\n".join(lines) + "\n").encode()


def _agent_toml(
    agent: AgentSource, native: CodexAgentNative, raw: dict[str, Any]
) -> bytes:
    values: dict[str, Any] = {
        "name": agent.name,
        "description": agent.description.strip(),
        "developer_instructions": agent.body.rstrip(),
    }
    if agent.effort in {"low", "medium", "high", "xhigh"}:
        values["model_reasoning_effort"] = agent.effort
    values.update(native.model_dump(exclude_none=True))
    overlap = set(raw) & set(values)
    if overlap:
        raise ValueError(
            "raw target fields shadow canonical or typed fields: "
            f"{', '.join(sorted(overlap))}"
        )
    values.update(raw)
    document = tomlkit.document()
    for key, value in values.items():
        document.add(key, value)
    return tomlkit.dumps(document).encode()


def _validate_patches(patch: NativePatch, generated: list[NativeValue]) -> None:
    validate_generated_conflicts(
        Patch(patch.operations),
        {value.pointer: value.value for value in generated},
    )


def compile_codex(ctx: SyncContext, sources: SourceBundle) -> Plan:
    root = ctx.codex
    files: list[OwnedFile] = []
    managed_roots: tuple[tuple[str, ManifestMode], ...] = (
        ("rules", "file"),
        ("skills", "dir"),
        ("agents", "file"),
    )
    trees = [
        OwnedTree(
            root / name, manifest_root=root / name, manifest_mode=mode, declaration=True
        )
        for name, mode in managed_roots
    ]
    diagnostics: list[Diagnostic] = []
    globals_ = [item for item in sources.globals if applies_to(item, "codex")]
    rules_ = [item for item in sources.rules if applies_to(item, "codex")]
    if globals_ or rules_:
        if globals_:
            global_source = globals_[0]
            value = block(global_source, "codex")
            diagnostics.extend(
                unhandled_target_block(global_source.path, "codex", value)
            )
            diagnostics.extend(omissions(global_source.path, "codex", value, set()))
        parts = [globals_[0].body.rstrip()] if globals_ else []
        parts.extend(rule.body.rstrip() for rule in rules_)
        files.append(
            OwnedFile(root / "AGENTS.md", ("\n\n".join(parts) + "\n").encode())
        )
    elif sources.globals or sources.rules:
        # Every global/rule was filtered by `only`. This host file is compiler-
        # owned whenever those sources exist, so retire it unconditionally.
        files.append(OwnedFile(root / "AGENTS.md", None))
    rules: list[tuple[str, CodexPrefixRule]] = []
    for rule in rules_:
        value = block(rule, "codex")
        native, issues = strict_native(rule.path, "codex", value, CodexRuleNative)
        diagnostics.extend(issues)
        if value.raw:
            diagnostics.append(
                Diagnostic("error", "codex raw rule fields are not valid", rule.path)
            )
        diagnostics.extend(omissions(rule.path, "codex", value, set()))
        if native:
            rules.extend((rule.path.name, item) for item in native.rules)
    if content := _rule_text(rules):
        files.append(
            OwnedFile(root / "rules" / "coding-agents.rules", content, root / "rules")
        )
    skill_paths: list[str] = []
    for skill in sources.skills:
        if not applies_to(skill, "codex"):
            continue
        value = block(skill, "codex")
        native, issues = strict_native(skill.path, "codex", value, CodexSkillNative)
        diagnostics.extend(issues)
        diagnostics.extend(
            omissions(
                skill.path,
                "codex",
                value,
                {
                    *({"paths"} if skill.paths else set()),
                    *(
                        {"disable_model_invocation"}
                        if skill.disable_model_invocation
                        else set()
                    ),
                },
            )
        )
        if native:
            meta, issues = frontmatter(
                skill.path,
                {
                    "name": skill.name,
                    "description": skill.description.replace("<", "").replace(">", ""),
                    **({"license": skill.license} if skill.license else {}),
                    **({"metadata": skill.metadata} if skill.metadata else {}),
                },
                native,
                value.raw,
            )
            diagnostics.extend(issues)
            trees.append(_tree(skill, root / "skills", meta))
            skill_paths.append(f"~/.codex/skills/{skill.source_dir.name}")
    for command in sources.commands:
        if not applies_to(command, "codex"):
            continue
        value = block(command, "codex")
        diagnostics.extend(unhandled_target_block(command.path, "codex", value))
        diagnostics.extend(omissions(command.path, "codex", value, {"command"}))
    agents = []
    for agent in sources.agents:
        if not applies_to(agent, "codex"):
            continue
        value = block(agent, "codex")
        native, issues = strict_native(agent.path, "codex", value, CodexAgentNative)
        diagnostics.extend(issues)
        diagnostics.extend(
            omissions(
                agent.path,
                "codex",
                value,
                {
                    *({"background"} if agent.background else set()),
                    *({"color"} if agent.color else set()),
                    *({"effort"} if agent.effort == "max" else set()),
                },
            )
        )
        if native:
            try:
                content = _agent_toml(agent, native, value.raw)
            except ValueError as exc:
                diagnostics.append(Diagnostic("error", str(exc), agent.path))
            else:
                files.append(
                    OwnedFile(
                        root / "agents" / f"{agent.stem}.toml", content, root / "agents"
                    )
                )
                agents.append(agent)
                if value.raw:
                    diagnostics.append(
                        Diagnostic(
                            "warning",
                            "using unvalidated raw target fields",
                            agent.path,
                        )
                    )
    if permissions := sources.permissions:
        value = block(permissions, "codex")
        diagnostics.extend(unhandled_target_block(permissions.paths[0], "codex", value))
        diagnostics.extend(
            omissions(
                permissions.paths[0],
                "codex",
                value,
                {
                    *({"tools"} if permissions.tools else set()),
                    *(
                        {"workspace"}
                        if permissions.workspace.allow or permissions.workspace.ask
                        else set()
                    ),
                    *({"secret_paths"} if permissions.secret_paths else set()),
                    *({"secret_names"} if permissions.secret_names else set()),
                },
            )
        )
        for path, targets, intent in permissions.command_targets:
            value = targets.root.get("codex", type(value)())
            diagnostics.extend(unhandled_target_block(path, "codex", value))
            diagnostics.extend(
                omissions(path, "codex", value, {"commands"} if intent else set())
            )
    native_values = [
        NativeValue(
            "codex",
            root / "config.toml",
            ("skills", "config"),
            [{"path": path, "enabled": True} for path in sorted(skill_paths)],
        )
    ]
    native_values.extend(
        value
        for agent in agents
        for value in (
            NativeValue(
                "codex",
                root / "config.toml",
                ("agents", agent.stem, "description"),
                agent.description.strip(),
            ),
            NativeValue(
                "codex",
                root / "config.toml",
                ("agents", agent.stem, "config_file"),
                f"~/.codex/agents/{agent.stem}.toml",
            ),
        )
    )
    patch, issues = native_patch(
        config_root=ctx.config_root,
        target="codex",
        path=root / "config.toml",
        patch_name="codex",
    )
    diagnostics.extend(issues)
    _validate_patches(patch, native_values)
    raw, raw_tree, raw_issues = raw_files(
        config_root=ctx.config_root,
        target="codex",
        root=root,
        excluded=(Path("config.toml"), Path("rules/coding-agents.rules")),
    )
    return Plan(
        tuple((*files, *raw)),
        tuple((*trees, raw_tree)),
        tuple(native_values),
        (patch,),
        tuple((*diagnostics, *raw_issues)),
    )
